### ISSUE TITLE
Doesn't work with "Compatibility" in Godot 4

### ISSUE THREAD

**Issue by ikonnow** [gdquest-demos/godot-4-stylized-sky#1]
I would like to request compatibility with the "Compatibility" rendering in Godot 4 for the stylized sky shader. Currently, the shader does not work properly when this option is enabled. This option is useful for testing projects on older hardware or platforms (/ XR mobile development) that do not support Vulkan. It would be great if the shader could be adapted to work with both modes. Thank you for your attention and your amazing work on this project.

**Comment by gtibo** [comment]
Hello, this shader has only been made in Forward+ for the moment, I'll probably add optimizations and other options in the future, but making it compatible with all renderers is not currently planned (unless of course someone propose a solution).
