### ISSUE TITLE
Black when switching scenes

### ISSUE THREAD

**Issue by DannyDevSe** [gdquest-demos/godot-4-stylized-sky#2]
When I switch scenes, the other scene with the skyshader is all black. I tried to change the process mode from auto to real time and the others, but that didn't work. Any clues on what's causing this? 
https://github.com/gdquest-demos/godot-4-stylized-sky/assets/102230735/5914cd97-4626-4e0c-bf52-b78d6cd60b79

**Comment by tailsc** [comment]
Appears to have been because the world environments were not local

**Comment by DannyDevSe** [comment]
Appears to be because if it's day in one scene and the next scene is also day, then it's black but if it's day to night it works and so to fix it make a new .tres for the other scene of the sky
